apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xanerh73b-go 
  janus-idp.io/tekton: xanerh73b-go
  backstage.io/kubernetes-id: xanerh73b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xanerh73b-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  